
name: CI

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.10.0

      # - name: executing ssh commands using ssh key
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.HOST}}
      #     username: ${{ secrets.USERNAME }}
      #     key: ${{ secrets.KEY }}
      #     script: |
      #       sudo su
      #       rm -rf anonymization-api
      #       git clone git@github.com:ahmedbesbes/anonymization-api.git
      #       cd anonymization-api
      #       sudo docker-compose down
      #       sudo docker-compose -f docker-compose.prod.yaml up --build -d
